/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author ashwi
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InsertStudent_Button = new javax.swing.JButton();
        AddResult_Button = new javax.swing.JButton();
        ListStudent_Button = new javax.swing.JButton();
        StudentResultList_Button = new javax.swing.JButton();
        UpdateMarks_Button = new javax.swing.JButton();
        Logout_Button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InsertStudent_Button.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        InsertStudent_Button.setText("Insert Student");
        InsertStudent_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertStudent_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(InsertStudent_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 37, 189, 37));

        AddResult_Button.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        AddResult_Button.setText("Add Result");
        AddResult_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddResult_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddResult_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 107, 189, 37));

        ListStudent_Button.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        ListStudent_Button.setText("List Student");
        ListStudent_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListStudent_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ListStudent_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 171, 189, 37));

        StudentResultList_Button.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        StudentResultList_Button.setText("List Student Result");
        StudentResultList_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentResultList_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(StudentResultList_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 239, 189, 37));

        UpdateMarks_Button.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        UpdateMarks_Button.setText("Update Student Marks");
        UpdateMarks_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateMarks_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateMarks_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 307, 189, 37));

        Logout_Button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Logout_Button.setText("LOGOUT");
        Logout_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Logout_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 86, 37));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/wp4720655-anime-school-aesthetic-wallpapers.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertStudent_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertStudent_ButtonActionPerformed
        // TODO add your handling code here:
        InsertStudent frame=new InsertStudent();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_InsertStudent_ButtonActionPerformed

    private void AddResult_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddResult_ButtonActionPerformed
        // TODO add your handling code here:
        InsertResult frame=new InsertResult();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_AddResult_ButtonActionPerformed

    private void ListStudent_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListStudent_ButtonActionPerformed
        // TODO add your handling code here:
        ListStudent frame=new ListStudent();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_ListStudent_ButtonActionPerformed

    private void StudentResultList_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentResultList_ButtonActionPerformed
        // TODO add your handling code here:
        ListStudentResult frame=new ListStudentResult();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_StudentResultList_ButtonActionPerformed

    private void UpdateMarks_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateMarks_ButtonActionPerformed
        // TODO add your handling code here:
        UpdateResult frame=new UpdateResult();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_UpdateMarks_ButtonActionPerformed

    private void Logout_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_ButtonActionPerformed
        // TODO add your handling code here:
        int response=JOptionPane.showConfirmDialog(null, "Are you sure you want to LOGOUT","submit", JOptionPane.YES_NO_OPTION);
        if(response==0){
            setVisible(false);
            homepage frame=new homepage();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_Logout_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddResult_Button;
    private javax.swing.JButton InsertStudent_Button;
    private javax.swing.JButton ListStudent_Button;
    private javax.swing.JButton Logout_Button;
    private javax.swing.JButton StudentResultList_Button;
    private javax.swing.JButton UpdateMarks_Button;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
